In [1]:
import pandas as pd
import numpy as np
import os

In [4]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [5]:
imp = IterativeImputer(random_state=0, max_iter=100)

In [8]:
features = [
    [4,2,1],
    [24,12,6],
    [8,np.nan,2],
    [28,14,7],
    [32,16,np.nan],
    [np.nan,60,30],
    [np.nan, np.nan, 1],
    [600,300,150]
]

In [9]:
imp.fit(features)

IterativeImputer(add_indicator=False, estimator=None,
                 imputation_order='ascending', initial_strategy='mean',
                 max_iter=100, max_value=None, min_value=None,
                 missing_values=nan, n_nearest_features=None, random_state=0,
                 sample_posterior=False, skip_complete=False, tol=0.001,
                 verbose=0)

In [10]:
imp.transform(features)

array([[  4.        ,   2.        ,   1.        ],
       [ 24.        ,  12.        ,   6.        ],
       [  8.        ,   3.99966003,   2.        ],
       [ 28.        ,  14.        ,   7.        ],
       [ 32.        ,  16.        ,   7.92735309],
       [120.00314828,  60.        ,  30.        ],
       [  5.58961593,   2.79614865,   1.        ],
       [600.        , 300.        , 150.        ]])

In [13]:
csv_path = os.path.join('datasets', 'data-prep')
diabetes_csv = os.path.join(csv_path, 'diabetes_processed_incomplete.csv')
diabetes = pd.read_csv(diabetes_csv)
diabetes.sample(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
492,4,99.0,68.000000,38.0,NaN,32.8,0.145,33,0
462,8,74.0,70.000000,40.0,49.0,35.3,0.705,39,0
657,1,120.0,80.000000,48.0,200.0,38.9,1.162,41,0
179,5,130.0,82.000000,32.0,NaN,39.1,0.956,37,1
233,4,122.0,68.000000,32.0,NaN,35.0,0.394,29,0
70,2,100.0,66.000000,20.0,90.0,32.9,0.867,28,1
181,0,119.0,64.000000,18.0,92.0,34.9,0.725,23,0
192,7,159.0,66.000000,32.0,NaN,30.4,0.383,36,1
441,2,83.0,66.000000,23.0,50.0,32.2,0.497,22,0
453,2,119.0,72.405184,32.0,NaN,19.6,0.832,72,0

In [15]:
diabetes.isnull().sum() #Indulin was remaining

Pregnancies                   0
Glucose                       0
BloodPressure                 0
SkinThickness                 0
Insulin                     374
BMI                           0
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [17]:
diabetes_features = diabetes.drop(['Outcome'], axis=1)
diabetes_label = diabetes[['Outcome']]

In [21]:
diabetes_features.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31
2,8,183.0,64.0,32.0,NaN,23.3,0.672,32
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33

In [22]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
imp = IterativeImputer(max_iter=10000, random_state=0)

In [23]:
imp.fit(diabetes_features)

IterativeImputer(add_indicator=False, estimator=None,
                 imputation_order='ascending', initial_strategy='mean',
                 max_iter=10000, max_value=None, min_value=None,
                 missing_values=nan, n_nearest_features=None, random_state=0,
                 sample_posterior=False, skip_complete=False, tol=0.001,
                 verbose=0)

In [24]:
diabetes_features_arr = imp.transform(diabetes_features)

In [25]:
diabetes_features_arr.shape

(768, 8)

In [26]:
diabetes_features = pd.DataFrame(diabetes_features_arr, columns=diabetes_features.columns)
diabetes_features.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6.0,148.0,72.0,35.0,219.028414,33.6,0.627,50.0
1,1.0,85.0,66.0,29.0,70.341550,26.6,0.351,31.0
2,8.0,183.0,64.0,32.0,270.573172,23.3,0.672,32.0
3,1.0,89.0,66.0,23.0,94.000000,28.1,0.167,21.0
4,0.0,137.0,40.0,35.0,168.000000,43.1,2.288,33.0

In [27]:
diabetes = pd.concat([diabetes_features, diabetes_label], axis=1)
diabetes.sample(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
338,9.0,152.0,78.0,34.0,171.000000,34.2,0.893,33.0,1
746,1.0,147.0,94.0,41.0,221.933398,49.3,0.358,27.0,1
683,4.0,125.0,80.0,32.0,152.954841,32.3,0.536,27.0,1
670,6.0,165.0,68.0,26.0,168.000000,33.6,0.631,49.0,0
335,0.0,165.0,76.0,43.0,255.000000,47.9,0.259,26.0,0

In [28]:
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,219.028414,33.6,0.627,50.0,1
1,1.0,85.0,66.0,29.0,70.341550,26.6,0.351,31.0,0
2,8.0,183.0,64.0,32.0,270.573172,23.3,0.672,32.0,1
3,1.0,89.0,66.0,23.0,94.000000,28.1,0.167,21.0,0
4,0.0,137.0,40.0,35.0,168.000000,43.1,2.288,33.0,1

In [29]:
diabetes.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [32]:
diabetes.to_csv(os.path.join(csv_path, 'diabetes_processed.csv'), index=False)

In [39]:
ls "datasets\data-prep"

 Volume in drive C is Windows
 Volume Serial Number is 2A82-BEAC

 Directory of C:\Users\pankaj\00_python_codes\Pluralsight\PythonProgramming\corepy\PythonPractise\datasets\data-prep

13-04-2020  12:44    <DIR>          .
13-04-2020  12:44    <DIR>          ..
12-04-2020  17:42            13,441 auto_mpg_processed.csv
12-04-2020  17:42            18,131 auto-mpg.csv
12-04-2020  17:42            25,336 cars.csv
12-04-2020  18:23            13,530 cars_processed.csv
12-04-2020  19:24            11,065 cars_processed2.csv
12-04-2020  17:42            23,873 diabetes.csv
13-04-2020  12:44            40,704 diabetes_processed.csv
13-04-2020  12:11            32,381 diabetes_processed_incomplete.csv
12-04-2020  17:42         1,616,446 GoSales_Tx_LogisticRegression.csv
               9 File(s)      1,794,907 bytes
               2 Dir(s)  667,817,402,368 bytes free